[Scope_5782_6channel_IQ_PID.vi]
Mixer freq \5BMHz\5D = "5,000000"
Mode = "Simulated"
Window = "1"
Unit = "V^2"
Trigger = "Software"
Output mixer fequency \5BMHz\5D = "352,000000"
Output delay = "0,000000"
ch0 DC offset = "0,000000"
ch1 DC offset = "0,000000"
#bins = "1"
Ki*T AM = "\00\00\00\00\00\00\00\00"
Kd/T AM = "\00\00\00\00\00\00\00\00"
Kp AM = "\00\00\00\00\00\00\00\00"
Feedback delay = "0"
Trigger delay = "0"
Acquire samples = "40000"
Cavity model = "TRUE"
w12 = "1357,168026"
R1 = "1560000000,000000"
w1 = "1476,548547"
Q1 = "100,000000"
K1 = "2,513274"
S = "1,000000"
ch1 DC offset 2 = "0,000000"
ch0 DC offset 2 = "0,000000"
ch3 DC offset = "0,000000"
ch2 DC offset = "0,000000"
Input delay 5761 = "0"
Kp Q = "\00\00\00\00\00\00\00\00"
Kd/T  Q = "\00\00\00\00\00\00\00\00"
Ki*T Q = "\00\00\00\00\00\00\00\00"
Output scale = "x1"
Input scale = "x1"
Host scale = "x1"
Input scale 5761 = "x1"
Host scale 5761 = "x1"
Virtual cavity = "FALSE"
Count to skip 5782, stage 1 = "0"
Count to skip 5761, stage 1 = "0"
K2 = "0,000000"
Q2 = "0,000000"
w2 = "0,000000"
K3 = "0,000000"
Q3 = "0,000000"
w3 = "0,000000"
w0 = "0,000000"
Piezo = "Off"
Measure Tau at Time = "0"
Tau set = "\00\00\00\00\00\00\00\00"
Count to skip 5782, stage 3 = "0"
Count to skip 5782, stage 2 = "0"
Count to skip 5761, stage 3 = "0"
Count to skip 5761, stage 2 = "0"
Fequency \5BkHz\5D = "0,000000"
a = "\00\00\00\00\00\00\00\00"
b = "\00\00\00\00\00\00\00\00"
w12 - b = "0,000000"
w12 - a = "0,000000"
w12 - dt = "0,000000"
w12 scale = "x1"
dw scale = "x1"
w12 LP  filter cutoff fequency = "0,000000"
dw LP filter cut off frequency = "0,000000"
ch1 delay = "0,000000"
ch3 delay = "0,000000"
Vi Vq LP  filter cutoff fequency = "0,000000"
Vfi Vfq LP filter cut off frequency = "0,000000"
Nforget = "0"
sigm = "0,000000"
Q0 - A = "0,000000"
Q0 - C = "0,000000"
Q0 - E = "0,000000"
Q0 - B = "0,000000"
Q0 - D = "0,000000"
Samples before reset = "0"
Reference fixed freq = "0,000000"
Lock in/out = "FALSE"

[Plots]
Upper graph.<size(s)> = "20"
Upper graph 0 = "TRUE"
Upper graph 1 = "TRUE"
Upper graph 2 = "FALSE"
Upper graph 3 = "FALSE"
Upper graph 4 = "FALSE"
Upper graph 5 = "FALSE"
Upper graph 6 = "TRUE"
Upper graph 7 = "TRUE"
Upper graph 8 = "FALSE"
Upper graph 9 = "FALSE"
Upper graph 10 = "FALSE"
Upper graph 11 = "FALSE"
Upper graph 12 = "FALSE"
Upper graph 13 = "FALSE"
Upper graph 14 = "FALSE"
Upper graph 15 = "FALSE"
Upper graph 16 = "TRUE"
Upper graph 17 = "TRUE"
Upper graph 18 = "TRUE"
Upper graph 19 = "FALSE"
Lower graph.<size(s)> = "20"
Lower graph 0 = "TRUE"
Lower graph 1 = "TRUE"
Lower graph 2 = "TRUE"
Lower graph 3 = "TRUE"
Lower graph 4 = "TRUE"
Lower graph 5 = "TRUE"
Lower graph 6 = "TRUE"
Lower graph 7 = "TRUE"
Lower graph 8 = "TRUE"
Lower graph 9 = "TRUE"
Lower graph 10 = "TRUE"
Lower graph 11 = "TRUE"
Lower graph 12 = "TRUE"
Lower graph 13 = "TRUE"
Lower graph 14 = "TRUE"
Lower graph 15 = "TRUE"
Lower graph 16 = "FALSE"
Lower graph 17 = "FALSE"
Lower graph 18 = "FALSE"
Lower graph 19 = "FALSE"
freqdata.<size(s)> = "20"
freqdata 0 = "TRUE"
freqdata 1 = "TRUE"
freqdata 2 = "TRUE"
freqdata 3 = "TRUE"
freqdata 4 = "TRUE"
freqdata 5 = "TRUE"
freqdata 6 = "TRUE"
freqdata 7 = "FALSE"
freqdata 8 = "FALSE"
freqdata 9 = "FALSE"
freqdata 10 = "FALSE"
freqdata 11 = "FALSE"
freqdata 12 = "FALSE"
freqdata 13 = "FALSE"
freqdata 14 = "FALSE"
freqdata 15 = "FALSE"
freqdata 16 = "FALSE"
freqdata 17 = "FALSE"
freqdata 18 = "FALSE"
freqdata 19 = "FALSE"
Adaptive FF graph.<size(s)> = "20"
Adaptive FF graph 0 = "TRUE"
Adaptive FF graph 1 = "TRUE"
Adaptive FF graph 2 = "TRUE"
Adaptive FF graph 3 = "TRUE"
Adaptive FF graph 4 = "TRUE"
Adaptive FF graph 5 = "TRUE"
Adaptive FF graph 6 = "TRUE"
Adaptive FF graph 7 = "TRUE"
Adaptive FF graph 8 = "TRUE"
Adaptive FF graph 9 = "TRUE"
Adaptive FF graph 10 = "TRUE"
Adaptive FF graph 11 = "TRUE"
Adaptive FF graph 12 = "TRUE"
Adaptive FF graph 13 = "TRUE"
Adaptive FF graph 14 = "TRUE"
Adaptive FF graph 15 = "TRUE"
Adaptive FF graph 16 = "FALSE"
Adaptive FF graph 17 = "FALSE"
Adaptive FF graph 18 = "FALSE"
Adaptive FF graph 19 = "FALSE"
Upper chart.<size(s)> = "20"
Upper chart 0 = "TRUE"
Upper chart 1 = "FALSE"
Upper chart 2 = "FALSE"
Upper chart 3 = "FALSE"
Upper chart 4 = "FALSE"
Upper chart 5 = "FALSE"
Upper chart 6 = "TRUE"
Upper chart 7 = "FALSE"
Upper chart 8 = "FALSE"
Upper chart 9 = "FALSE"
Upper chart 10 = "FALSE"
Upper chart 11 = "FALSE"
Upper chart 12 = "FALSE"
Upper chart 13 = "FALSE"
Upper chart 14 = "TRUE"
Upper chart 15 = "TRUE"
Upper chart 16 = "TRUE"
Upper chart 17 = "TRUE"
Upper chart 18 = "TRUE"
Upper chart 19 = "FALSE"
Lower chart.<size(s)> = "20"
Lower chart 0 = "TRUE"
Lower chart 1 = "TRUE"
Lower chart 2 = "TRUE"
Lower chart 3 = "TRUE"
Lower chart 4 = "TRUE"
Lower chart 5 = "TRUE"
Lower chart 6 = "TRUE"
Lower chart 7 = "FALSE"
Lower chart 8 = "FALSE"
Lower chart 9 = "FALSE"
Lower chart 10 = "FALSE"
Lower chart 11 = "FALSE"
Lower chart 12 = "FALSE"
Lower chart 13 = "FALSE"
Lower chart 14 = "FALSE"
Lower chart 15 = "FALSE"
Lower chart 16 = "FALSE"
Lower chart 17 = "FALSE"
Lower chart 18 = "FALSE"
Lower chart 19 = "FALSE"

[Scope_5782_6channel_IQ_PID_Quench.vi]
Mixer freq \5BMHz\5D = "5,000000"
Mode = "Simulated"
Window = "1"
Unit = "V^2"
Trigger = "Software"
Output mixer fequency \5BMHz\5D = "352,000000"
Output delay = "0,000000"
ch0 DC offset = "0,000000"
ch1 DC offset = "0,000000"
#bins = "1"
Ki*T AM = "\00\00\00\00\00\00\00\00"
Kd/T AM = "\00\00\00\00\00\00\00\00"
Kp AM = "\00\00\00\00\00\00\00\00"
Feedback delay = "0"
Trigger delay = "0"
Acquire samples = "40000"
Cavity model = "FALSE"
w12 = "1357,168026"
R1 = "1560000000,000000"
w1 = "1476,548547"
Q1 = "100,000000"
K1 = "2,513274"
S = "1,000000"
ch1 DC offset 2 = "0,000000"
ch0 DC offset 2 = "0,000000"
ch3 DC offset = "0,000000"
ch2 DC offset = "0,000000"
Input delay 5761 = "0"
Kp Q = "\00\00\00\00\00\00\00\00"
Kd/T  Q = "\00\00\00\00\00\00\00\00"
Ki*T Q = "\00\00\00\00\00\00\00\00"
Output scale = "x1"
Input scale = "x1"
Host scale = "x1"
Input scale 5761 = "x1"
Host scale 5761 = "x1"
Virtual cavity = "FALSE"
Count to skip 5782, stage 1 = "0"
Count to skip 5761, stage 1 = "0"
K2 = "0,000000"
Q2 = "0,000000"
w2 = "0,000000"
K3 = "0,000000"
Q3 = "0,000000"
w3 = "0,000000"
w0 = "0,000000"
Piezo = "Off"
Measure Tau at Time = "0"
Tau set = "\00\00\00\00\00\00\00\00"
Count to skip 5782, stage 3 = "0"
Count to skip 5782, stage 2 = "0"
Count to skip 5761, stage 3 = "0"
Count to skip 5761, stage 2 = "0"
Fequency \5BkHz\5D = "0,000000"
a = "\00\00\00\00\00\00\00\00"
b = "\00\00\00\00\00\00\00\00"
w12 - b = "0,000000"
w12 - a = "0,000000"
w12 - dt = "0,000000"
w12 scale = "x1"
dw scale = "x1"
w12 LP  filter cutoff fequency = "0,000000"
dw LP filter cut off frequency = "0,000000"
ch1 delay = "0,000000"
ch3 delay = "0,000000"
Vi Vq LP  filter cutoff fequency = "0,000000"
Vfi Vfq LP filter cut off frequency = "0,000000"
Nforget = "0"
sigm = "0,000000"
Q0 - A = "0,000000"
Q0 - C = "0,000000"
Q0 - E = "0,000000"
Q0 - B = "0,000000"
Q0 - D = "0,000000"
Samples before reset = "0"
Reference fixed freq = "0,000000"
Lock in/out = "FALSE"